/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**     
 *
 * @author Mukuria
 */
public final class Doctor extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement prs=null;

   
 
 
   
       public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        Issued.setText((month+1)+"/"+day+"/"+year);
        
        
    }
    private JFrame frame;
    

    /**
     * Creates new form Doctor
     */
  
    public Doctor() {
        
        initComponents();
        Comboitems();
        currentDate ();
        
    }
    
       public void Comboitems(){
  try{
    Class.forName("com.mysql.jdbc.Driver");
   con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
   Statement stat=con.createStatement();
   
    String SelectQuery="SELECT `Name` FROM `medicine` ";
  ResultSet  rlts=stat.executeQuery(SelectQuery);
   // ComboBox.removeAllItems();
      while(rlts.next()){
         
          ComboBox.addItem(rlts.getString("Name")); 
      }
  }catch(Exception e){
  System.out.println(e);
  
  
  }
        }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        Exp = new javax.swing.JTextField();
        Issued = new javax.swing.JTextField();
        Ref = new javax.swing.JTextField();
        Dose = new javax.swing.JTextField();
        Effects = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        Daily = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Machine = new javax.swing.JTextField();
        Using = new javax.swing.JTextField();
        PatientId = new javax.swing.JTextField();
        Storage = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Prescription = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescription = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Reference No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Dose(mg)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Number of Tablets");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Issued Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Exp Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Daily Dose");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Side Effects");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Storage Advice");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Driving and Using Machines");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("How to Use Medication");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Patient ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Patient Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 0));
        jLabel13.setText("Date of Birth");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 0));
        jLabel15.setText("Name of Tablet");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        ComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 130, 30));

        Exp.setEditable(false);
        jPanel1.add(Exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, 30));

        Issued.setEditable(false);
        Issued.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                IssuedCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        Issued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuedActionPerformed(evt);
            }
        });
        jPanel1.add(Issued, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, 30));

        Ref.setEditable(false);
        Ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefActionPerformed(evt);
            }
        });
        jPanel1.add(Ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, 30));

        Dose.setEditable(false);
        Dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoseActionPerformed(evt);
            }
        });
        jPanel1.add(Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, 30));

        Effects.setEditable(false);
        Effects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EffectsActionPerformed(evt);
            }
        });
        jPanel1.add(Effects, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 130, 30));

        Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberActionPerformed(evt);
            }
        });
        jPanel1.add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 130, 30));

        Daily.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Daily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyActionPerformed(evt);
            }
        });
        jPanel1.add(Daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, 30));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        jPanel1.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 130, 30));

        Machine.setEditable(false);
        Machine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(Machine, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 130, 30));

        Using.setEditable(false);
        Using.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Using.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsingActionPerformed(evt);
            }
        });
        jPanel1.add(Using, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 130, 30));

        PatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIdActionPerformed(evt);
            }
        });
        jPanel1.add(PatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 130, 30));

        Storage.setEditable(false);
        Storage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Storage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StorageActionPerformed(evt);
            }
        });
        jPanel1.add(Storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 130, 30));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 130, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, 60));

        Prescription.setBackground(new java.awt.Color(204, 255, 255));
        Prescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Prescription.setForeground(new java.awt.Color(51, 0, 153));
        Prescription.setText("Prescription");
        Prescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(Prescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));

        Print.setBackground(new java.awt.Color(204, 255, 255));
        Print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(51, 0, 153));
        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 470, -1, -1));

        prescription.setEditable(false);
        prescription.setColumns(20);
        prescription.setLineWrap(true);
        prescription.setRows(5);
        prescription.setWrapStyleWord(true);
        prescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(prescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 300, 400));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 540, -1, 60));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 757));

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "KIM'S HEALTH CENTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 48), new java.awt.Color(102, 102, 0))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1360, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        try{
            prescription.print();
        }catch(PrinterException ex){
            Logger.getLogger(Doctor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void PrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescriptionActionPerformed
        // TODO add your handling code here:
        String qty1=(Ref.getText());
        String qty2=(Dose.getText());
        String qty3=(Number.getText());
        String qty4=(Issued.getText());
        String qty5=(Exp.getText());
        String qty6=(Daily.getText());
        String qty7=(Effects.getText());
        String qty8=(Machine.getText());
        String qty9=(Using.getText());
        String qty10=(Storage.getText());
        String qty11=(PatientId.getText());
        String qty12=(Name.getText());
        String qty13=(DOB.getText());
        String qty14=( (String)ComboBox.getSelectedItem());
        prescription.setText("");
        prescription.append("\tKIM'S HEALTH CENTER\n\n\n"
            + "\nPatient Name:\t"   +qty12
            +"\tDate of Birth:"   +qty13
            + "\nPatient Id:\t"   +qty11
            +"\n\n\nPrescription:\t"   +qty14
            + "\nReference no:\t"   +qty1
            +"\nDose (mg):\t"   +qty2
            + "\nDaily Dose:\t"   +qty6
            +"\nIssued Date:\t"   +qty4
            +"\nExpiry Date:\t"   +qty5
            +"\nNo of Tablets:\t"   +qty3
            +"\nside effects:\t"   +qty7
            +"\nDriving/Using Machine:\t"   +qty8
           +"\nStorage Advice:\t"   +qty10
            +"\nHow to Use Medication:" +qty9
            +"\n\n\nTo contact us call on:0724956789\nor email us on:kim@yahoo.com"
        );

        //

    }//GEN-LAST:event_PrescriptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void StorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StorageActionPerformed

    private void UsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsingActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberActionPerformed

    private void EffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EffectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EffectsActionPerformed

    private void DoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoseActionPerformed

    private void RefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefActionPerformed

    private void IssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuedActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_IssuedActionPerformed

    private void IssuedCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_IssuedCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_IssuedCaretPositionChanged

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void ComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboBoxPopupMenuWillBecomeInvisible
        //TODO add your handling code here:
        String medicine=(String)ComboBox.getSelectedItem();
        String sql="SELECT * FROM `medicine` where name=?";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
            prs=con.prepareStatement(sql);
            prs.setString(1, medicine);
            ResultSet rlts=prs.executeQuery();
            if(rlts.next()){
                String ref=rlts.getString("Ref");
                Ref.setText(ref);
                String dose=rlts.getString("Dose");
                Dose.setText(dose);
                String exp=rlts.getString("Exp");
                Exp.setText(exp);
                String effects=rlts.getString("Effects");
                Effects.setText(effects);
                String machine=rlts.getString("Machine");
                Machine.setText(machine);
                String using=rlts.getString("Using");
                Using.setText(using);
                String storage=rlts.getString("Storage");
                Storage.setText(storage);
                rlts.close();
                prs.close();
            }//
        } catch (Exception e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ComboBoxPopupMenuWillBecomeInvisible

    private void PatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIdActionPerformed

    private void DailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DailyActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField Daily;
    private javax.swing.JTextField Dose;
    private javax.swing.JTextField Effects;
    private javax.swing.JTextField Exp;
    private javax.swing.JTextField Issued;
    private javax.swing.JTextField Machine;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JTextField PatientId;
    private javax.swing.JButton Prescription;
    private javax.swing.JButton Print;
    private javax.swing.JTextField Ref;
    private javax.swing.JTextField Storage;
    private javax.swing.JTextField Using;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea prescription;
    // End of variables declaration//GEN-END:variables

    Object fname() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getFirstname() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object Surname() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object IDNo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getSurname() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getemail() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getIDNo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getPhone() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
