/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukuria
 */
public class Login extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement prs=null;
    ResultSet rlts=null;
    /* PreparedStatement pst=null;
    ResultSet rs=null;
     Connection con=null;


    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
      public void loginchecker(){
       String Username=username.getText();
       String Password=password.getText();
       if(Username.isEmpty() || Password.isEmpty()){
           JOptionPane.showMessageDialog(this, "Please ensure you fill all the fields before proceeding");
          
       }
       else{
           String sql="SELECT * FROM `Doctor` WHERE `Firstname`=? AND`IDNo`=?";
           try {
               con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               prs=con.prepareStatement(sql);
               prs.setString(1, Username);
               prs.setString(2,Password);
               rlts=prs.executeQuery();
               if(rlts.next()){
               
                setVisible(false);
                Doctor ob=new Doctor();
               ob.setVisible(true);
               rlts.close();
               prs.close();
                 
               }
               else{
                   JOptionPane.showMessageDialog(this, "wrong Firstname or Password! ");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
      }
            public void loginchecker1(){
       String Username=username.getText();
       String Password=password.getText();
       if(Username.isEmpty() || Password.isEmpty()){
           JOptionPane.showMessageDialog(this, "Please ensure you fill all the fields before proceeding");
       }
       else{
           String sql="SELECT * FROM `Patient` WHERE `Firstname`=? AND`IDNo`=?";
           try {
               con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               prs=con.prepareStatement(sql);
               prs.setString(1, Username);
               prs.setString(2,Password);
               rlts=prs.executeQuery();
               if(rlts.next()){
               
                setVisible(false);
                Patient ob=new Patient();
               ob.setVisible(true);
               rlts.close();
               prs.close();
                 
               }
               else{
                   JOptionPane.showMessageDialog(this, "wrong Firstname or Password! ");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
            }
            public void loginchecker2(){
       String Username=username.getText();
       String Password=password.getText();
       if(Username.isEmpty() || Password.isEmpty()){
           JOptionPane.showMessageDialog(this, "Please ensure you fill all the fields before proceeding");
       }
       else{
           String sql="SELECT * FROM `Admin` WHERE `Firstname`=? AND`IDNo`=?";
           try {
               con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               prs=con.prepareStatement(sql);
               prs.setString(1, Username);
               prs.setString(2,Password);
               rlts=prs.executeQuery();
               if(rlts.next()){
               
                setVisible(false);
                Admin ob=new Admin();
               ob.setVisible(true);
               rlts.close();
               prs.close();
                 
               }
               else{
                   JOptionPane.showMessageDialog(this, "wrong Firstname or Password! ");
               }
           } catch (SQLException ex) {
               Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       

       }
       }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        comboBox = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 800));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 700));
        jPanel1.setLayout(null);

        username.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(680, 90, 234, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Firstname");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 80, 243, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Password/IdNo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 190, 390, 58);

        Login.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Login.setText("login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(610, 430, 109, 64);

        password.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(680, 180, 234, 54);

        comboBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login as;", "A Doctor", "Patient", "Admin" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox);
        comboBox.setBounds(690, 270, 170, 66);

        Back.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(890, 430, 120, 70);

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "KIM'S HEALTH CENTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 48), new java.awt.Color(102, 102, 0))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1360, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        switch (comboBox.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(this, "Please Select whom you want to log in as");
                break;
            case 1:
                loginchecker();
                break;
            case 2:
                loginchecker1();
                break;
            default:
                loginchecker2();
                break; 
        }
       
      
    }//GEN-LAST:event_LoginActionPerformed
       
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxActionPerformed
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
