/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukuria
 */
public final class Patient extends javax.swing.JFrame {
      Connection con=null;
    PreparedStatement prs=null;
    ResultSet rlts=null;


    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
         Comboitems();
    }
public void Comboitems(){
  try{
    Class.forName("com.mysql.jdbc.Driver");
   con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
   Statement stat=con.createStatement();
   
    String SelectQuery="SELECT * FROM `doctor` ";
  ResultSet  rlts=stat.executeQuery(SelectQuery);
   // ComboBox.removeAllItems();
      while(rlts.next()){
         
          doc.addItem(rlts.getString("Firstname") + "  " +rlts.getString("Surname")); 
      }
  }catch(Exception e){
  System.out.println(e);
  
  
  }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        REpassword1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        REpassword = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        appointment = new javax.swing.JTextField();
        REpassword4 = new javax.swing.JLabel();
        doc = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        REpassword5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 192, 40));

        jLabel4.setBackground(new java.awt.Color(242, 38, 19));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Surname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 60));

        jLabel1.setBackground(new java.awt.Color(242, 38, 19));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("First name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, 50));

        firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 192, 40));

        REpassword1.setBackground(new java.awt.Color(242, 38, 19));
        REpassword1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REpassword1.setForeground(new java.awt.Color(255, 153, 0));
        REpassword1.setText("Doctor's name");
        getContentPane().add(REpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, 50));

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 192, 40));

        REpassword.setBackground(new java.awt.Color(242, 38, 19));
        REpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REpassword.setForeground(new java.awt.Color(255, 153, 0));
        REpassword.setText("Phone no");
        getContentPane().add(REpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, 50));

        phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 192, 40));

        Back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 0, 255));
        Back.setText("Logout");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, -1, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, -1, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 255));
        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, 50));

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 192, 40));

        appointment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentActionPerformed(evt);
            }
        });
        getContentPane().add(appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 192, 40));

        REpassword4.setBackground(new java.awt.Color(242, 38, 19));
        REpassword4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REpassword4.setForeground(new java.awt.Color(255, 153, 0));
        REpassword4.setText("Appointmnt date");
        getContentPane().add(REpassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, 50));

        doc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doc.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                docPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                docPopupMenuWillBecomeVisible(evt);
            }
        });
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        getContentPane().add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 190, 40));

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "KIM'S HEALTH CENTER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 48), new java.awt.Color(102, 102, 0))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1360, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        REpassword5.setBackground(new java.awt.Color(242, 38, 19));
        REpassword5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REpassword5.setForeground(new java.awt.Color(255, 153, 0));
        REpassword5.setText("Email");
        getContentPane().add(REpassword5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 50));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1360, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
         setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        firstname.setText(null);
       phone.setText(null);
        surname.setText(null);
        phone.setText(null);
         date.setText(null);
        email.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String Firstname=firstname.getText();
        String Surname=surname.getText();
        String Phone=phone.getText();
        String Email=email.getText();
        String Date=date.getText(); 
        String Appointment=appointment.getText();
        String doctor=doc.getSelectedItem().toString();

        if(Firstname.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter Firstname!");
        }
        else if(Surname.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter a Surname!");
        }
       
        else if(Phone.equals(""))
        {
            JOptionPane.showMessageDialog(null," Enter Your Phone number!");
        }

        else
        {

            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                String path= "jdbc:mysql://localhost/Hospital";
                String user="root";
                String pass="";
                Connection conn=DriverManager.getConnection(path,user,pass);
                Statement St=conn.createStatement();
                String query = "INSERT INTO `appointment` (`Firstname`, `Surname`, `Phone_no`, `email`,`Date`,`Reason`,`Doctor`"
                        + " ) VALUES ('"+Firstname+"','"+Surname+"','"+Phone+"','"+Email+"','"+Date+"','"+Appointment+"','"+doctor+"')";
                St.executeUpdate(query);

                JOptionPane.showMessageDialog(null,"Appointment Booked successfully");
                prs.close();
                rlts.close();
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error In Connection!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentActionPerformed

    private void docPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_docPopupMenuWillBecomeInvisible
        //TODO add your handling code here:
        
    }//GEN-LAST:event_docPopupMenuWillBecomeInvisible

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docActionPerformed

    private void docPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_docPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_docPopupMenuWillBecomeVisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel REpassword;
    private javax.swing.JLabel REpassword1;
    private javax.swing.JLabel REpassword4;
    private javax.swing.JLabel REpassword5;
    private javax.swing.JTextField appointment;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> doc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
